# Generated by Django 4.1.13 on 2025-12-04 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj_cpf', models.CharField(max_length=18, unique=True, verbose_name='CNPJ/CPF')),
                ('nome_fantasia', models.CharField(max_length=255, verbose_name='Nome da Empresa')),
                ('cep', models.CharField(max_length=9)),
                ('logradouro', models.CharField(max_length=255)),
                ('pontos_acumulados', models.IntegerField(default=0)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='parceiros/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_parceiro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PontoColeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_local', models.CharField(help_text='Ex: Ecoponto Central', max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('endereco_completo', models.CharField(max_length=255)),
                ('itens_coletados_total', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('parceiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontos_coleta', to='app.parceiro')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(help_text='Ex: Celular Samsung Antigo', max_length=50)),
                ('tipo', models.CharField(choices=[('Metal', 'Metal'), ('Plastico', 'Plástico'), ('Vidro', 'Vidro'), ('Eletronico', 'Eletrônico'), ('Papel', 'Papel')], max_length=50)),
                ('valor', models.FloatField(default=0.0, help_text='Valor em pontos ou moeda')),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('ponto_coleta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.pontocoleta')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('itens_descartados', models.IntegerField(default=0)),
                ('pontos', models.IntegerField(default=0)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='clientes/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_cliente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
